import { BrewRecipe } from "./types";

export const DEFAULT_PRESET_RECIPES: BrewRecipe[] = [
  {
    id: "preset-v60-hoffmann",
    name: "Ultimate V60 (James Hoffmann)",
    brewMethod: "v60",
    description: "The standard technique for clean, high-extraction clarity with medium-fine grind.",
    author: "James Hoffmann",
    coffeeDoseGrams: 30,
    waterAmountGrams: 500,
    ratio: 16.67,
    grindSize: "Medium-Fine (e.g. Fellow Ode 4.1)",
    waterTempCelsius: 98,
    totalTimeSeconds: 210,
    isPreset: true,
    isFavorite: true,
    createdAt: new Date().toISOString(),
    stages: [
      {
        id: "s1",
        name: "Bloom",
        startSecond: 0,
        durationSeconds: 45,
        targetWaterWeightGrams: 60,
        instruction: "Pour 60g (2x coffee weight) quickly. Swirl gently to ensure all coffee grounds are fully wet.",
        stageType: "bloom",
      },
      {
        id: "s2",
        name: "Main Pour Phase 1 (60%)",
        startSecond: 45,
        durationSeconds: 30,
        targetWaterWeightGrams: 300,
        instruction: "Pour gently in concentric circles up to 300g by 1:15.",
        stageType: "pour",
      },
      {
        id: "s3",
        name: "Main Pour Phase 2 (100%)",
        startSecond: 75,
        durationSeconds: 30,
        targetWaterWeightGrams: 500,
        instruction: "Continue pouring gently to reach 500g total weight by 1:45.",
        stageType: "pour",
      },
      {
        id: "s4",
        name: "Gentle Stir & Swirl",
        startSecond: 105,
        durationSeconds: 15,
        targetWaterWeightGrams: 500,
        instruction: "Give one gentle clockwise and counter-clockwise stir with a spoon, then a gentle swirl to flatten the bed.",
        stageType: "agitation",
      },
      {
        id: "s5",
        name: "Drawdown",
        startSecond: 120,
        durationSeconds: 90,
        targetWaterWeightGrams: 500,
        instruction: "Allow coffee to draw down completely until the bed is dry and flat.",
        stageType: "drawdown",
      },
    ],
  },
  {
    id: "preset-v60-kasuya-46",
    name: "4:6 Method V60 (Tetsu Kasuya)",
    brewMethod: "v60",
    description: "World Brewers Cup Champion method using coarse grind and 5 discrete pulses to tune sweetness, acidity, and strength.",
    author: "Tetsu Kasuya",
    coffeeDoseGrams: 20,
    waterAmountGrams: 300,
    ratio: 15,
    grindSize: "Coarse (e.g. Comandante 28 clicks)",
    waterTempCelsius: 92,
    totalTimeSeconds: 210,
    isPreset: true,
    createdAt: new Date().toISOString(),
    stages: [
      {
        id: "k1",
        name: "1st Pour (Acidity Balance)",
        startSecond: 0,
        durationSeconds: 45,
        targetWaterWeightGrams: 50,
        instruction: "Pour 50g slowly in small circles. Adjust this amount for sweetness vs acidity.",
        stageType: "bloom",
      },
      {
        id: "k2",
        name: "2nd Pour (Sweetness & Body)",
        startSecond: 45,
        durationSeconds: 45,
        targetWaterWeightGrams: 120,
        instruction: "Pour to 120g (+70g). Wait until water drains completely through.",
        stageType: "pour",
      },
      {
        id: "k3",
        name: "3rd Pour (Strength)",
        startSecond: 90,
        durationSeconds: 40,
        targetWaterWeightGrams: 180,
        instruction: "Pour to 180g (+60g).",
        stageType: "pour",
      },
      {
        id: "k4",
        name: "4th Pour (Strength)",
        startSecond: 130,
        durationSeconds: 40,
        targetWaterWeightGrams: 240,
        instruction: "Pour to 240g (+60g).",
        stageType: "pour",
      },
      {
        id: "k5",
        name: "5th Pour (Final Yield)",
        startSecond: 170,
        durationSeconds: 40,
        targetWaterWeightGrams: 300,
        instruction: "Pour to 300g (+60g). Let drain completely.",
        stageType: "drawdown",
      },
    ],
  },
  {
    id: "preset-aeropress-inverted",
    name: "AeroPress Inverted (Rich & Juicy)",
    brewMethod: "aeropress",
    description: "Inverted method allowing full immersion steeping with zero premature drip.",
    author: "Specialty Standard",
    coffeeDoseGrams: 15,
    waterAmountGrams: 225,
    ratio: 15,
    grindSize: "Medium-Fine",
    waterTempCelsius: 90,
    totalTimeSeconds: 150,
    isPreset: true,
    isFavorite: true,
    createdAt: new Date().toISOString(),
    stages: [
      {
        id: "ap1",
        name: "Pour & Wet Grounds",
        startSecond: 0,
        durationSeconds: 20,
        targetWaterWeightGrams: 225,
        instruction: "Pour all 225g water rapidly into inverted AeroPress.",
        stageType: "bloom",
      },
      {
        id: "ap2",
        name: "Agitate / Stir",
        startSecond: 20,
        durationSeconds: 20,
        targetWaterWeightGrams: 225,
        instruction: "Stir vigorously back and forth 5 times. Attach rinsed filter cap.",
        stageType: "agitation",
      },
      {
        id: "ap3",
        name: "Immersion Steep",
        startSecond: 40,
        durationSeconds: 60,
        targetWaterWeightGrams: 225,
        instruction: "Let coffee steep. At 1:40, carefully flip AeroPress onto server/mug.",
        stageType: "other",
      },
      {
        id: "ap4",
        name: "Gentle Press",
        startSecond: 100,
        durationSeconds: 30,
        targetWaterWeightGrams: 225,
        instruction: "Press down smoothly for 30s until you hear the first hiss of air. Stop immediately.",
        stageType: "press",
      },
    ],
  },
  {
    id: "preset-flair-espresso",
    name: "Flair 58 Lever Extraction (Pre-infusion & Declining Flow)",
    brewMethod: "flair",
    description: "Manual lever espresso profiling with soft pre-infusion, 9 bar peak, and tapering declining pressure.",
    author: "Flair Espresso",
    coffeeDoseGrams: 18,
    waterAmountGrams: 38,
    ratio: 2.1,
    grindSize: "Fine Espresso",
    waterTempCelsius: 94,
    totalTimeSeconds: 45,
    isPreset: true,
    isFavorite: true,
    createdAt: new Date().toISOString(),
    stages: [
      {
        id: "fl1",
        name: "Pre-infusion (2-3 Bar)",
        startSecond: 0,
        durationSeconds: 12,
        targetWaterWeightGrams: 5,
        instruction: "Gently lower lever to achieve 2-3 bar until the entire bottom of the basket is saturated.",
        stageType: "bloom",
      },
      {
        id: "fl2",
        name: "Ramp to Peak (8-9 Bar)",
        startSecond: 12,
        durationSeconds: 15,
        targetWaterWeightGrams: 24,
        instruction: "Smoothly apply pressure up to 8-9 bar for rich crema and maximum sweetness.",
        stageType: "pour",
      },
      {
        id: "fl3",
        name: "Declining Pressure (6 -> 4 Bar)",
        startSecond: 27,
        durationSeconds: 18,
        targetWaterWeightGrams: 38,
        instruction: "Ease off pressure down to 5-6 bar and finish at 4 bar as puck resistance decreases. Target 38g yield.",
        stageType: "pour",
      },
    ],
  },
];
