import { TastingLog, BrewMethodType } from "@brewlog/core";
import { TastingLogRow, TastingLogInsert } from "../database.types";

export const mapTastingLogRowToDomain = (l: TastingLogRow): TastingLog => ({
  id: l.id,
  userId: l.user_id,
  beanId: l.bean_id || "sample",
  recipeId: l.recipe_id || "sample",
  grinderId: l.grinder_id || undefined,
  brewerId: l.brewer_id || undefined,
  grinderSnapshot: l.grinder_snapshot || undefined,
  brewerSnapshot: l.brewer_snapshot || undefined,
  beanNameSnapshot: l.bean_name_snapshot,
  roasterSnapshot: l.roaster_snapshot,
  recipeNameSnapshot: l.recipe_name_snapshot,
  brewMethod: l.brew_method as BrewMethodType,
  brewDate: l.brew_date,
  coffeeDoseGrams: Number(l.coffee_dose_grams),
  waterAmountGrams: Number(l.water_amount_grams),
  actualTimeSeconds: l.actual_time_seconds,
  grindSetting: l.grind_setting,
  waterTempCelsius: l.water_temp_celsius,
  scores: {
    fragranceAroma: Number(l.fragrance_aroma),
    flavor: Number(l.flavor ?? 7.5),
    aftertaste: Number(l.aftertaste),
    acidity: Number(l.acidity),
    body: Number(l.body),
    balance: Number(l.balance),
    uniformity: Number(l.uniformity ?? 10.0),
    cleanCup: Number(l.clean_cup ?? l.clarity ?? 10.0),
    sweetness: Number(l.sweetness),
    overall: Number(l.overall),
    clarity: l.clarity !== undefined && l.clarity !== null ? Number(l.clarity) : undefined,
  },
  calculatedScaScore: Number(l.calculated_sca_score),
  rating: Number(l.rating),
  flavorTags: l.flavor_tags || [],
  notes: l.notes,
  wouldBrewAgain: l.would_brew_again,
  createdAt: l.created_at,
});

export const mapTastingLogDomainToInsert = (
  log: Omit<TastingLog, "id" | "createdAt">,
  userId: string
): TastingLogInsert => ({
  user_id: userId,
  bean_name_snapshot: log.beanNameSnapshot,
  roaster_snapshot: log.roasterSnapshot,
  recipe_name_snapshot: log.recipeNameSnapshot,
  brew_method: log.brewMethod,
  brew_date: log.brewDate,
  coffee_dose_grams: log.coffeeDoseGrams,
  water_amount_grams: log.waterAmountGrams,
  actual_time_seconds: log.actualTimeSeconds,
  grind_setting: log.grindSetting,
  water_temp_celsius: log.waterTempCelsius,
  fragrance_aroma: log.scores.fragranceAroma,
  flavor: log.scores.flavor,
  aftertaste: log.scores.aftertaste,
  acidity: log.scores.acidity,
  body: log.scores.body,
  balance: log.scores.balance,
  uniformity: log.scores.uniformity,
  clean_cup: log.scores.cleanCup,
  sweetness: log.scores.sweetness,
  overall: log.scores.overall,
  clarity: log.scores.cleanCup,
  calculated_sca_score: log.calculatedScaScore,
  rating: log.rating,
  flavor_tags: log.flavorTags,
  notes: log.notes,
  would_brew_again: log.wouldBrewAgain,
});

