import { Bean, Equipment, TastingLog, DEFAULT_PRESET_RECIPES } from '@brewlog/core';

export const INITIAL_BEANS: Bean[] = [
  {
    id: 'bean-1',
    name: 'Worka Sakaro Anaerobic',
    roaster: 'Sey Coffee',
    originCountry: 'Ethiopia',
    region: 'Gedeb, Yirgacheffe',
    farm: 'Worka Sakaro Washing Station',
    variety: ['Kurume', 'Dega'],
    altitudeMeters: 2100,
    process: 'anaerobic-natural',
    roastLevel: 'light',
    roastDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 12 days ago
    flavorNotes: ['Jasmine', 'Peach', 'Bergamot', 'Papaya'],
    rating: 4.8,
    bagWeightGrams: 250,
    remainingGrams: 180,
    price: 24.0,
    isFavorite: true,
    notes: 'Incredible clarity and floral sweetness. Best on V60 at 96°C.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bean-2',
    name: 'El Paraiso Lychee',
    roaster: 'Manhattan Coffee Roasters',
    originCountry: 'Colombia',
    region: 'Cauca',
    farm: 'Finca El Paraiso (Diego Bermudez)',
    variety: ['Castillo'],
    altitudeMeters: 1930,
    process: 'experimental',
    roastLevel: 'light',
    roastDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 6 days ago
    flavorNotes: ['Lychee', 'Rose', 'Raspberry', 'Vanilla Bean'],
    rating: 4.9,
    bagWeightGrams: 250,
    remainingGrams: 220,
    price: 28.5,
    isFavorite: true,
    notes: 'Thermal shock processing gives an intense perfume aroma of lychee candy.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bean-3',
    name: 'Kainamui Peaberry',
    roaster: 'Tim Wendelboe',
    originCountry: 'Kenya',
    region: 'Kirinyaga',
    farm: 'Kainamui Factory',
    variety: ['SL28', 'SL34', 'Ruiru 11'],
    altitudeMeters: 1750,
    process: 'washed',
    roastLevel: 'light',
    roastDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 25 days ago
    flavorNotes: ['Blackberry', 'Grapefruit', 'Black Tea'],
    rating: 4.7,
    bagWeightGrams: 250,
    remainingGrams: 90,
    price: 22.0,
    isFavorite: false,
    notes: 'Juicy, sparkling phosphoric acidity. Great for AeroPress bypass.',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_EQUIPMENT: Equipment[] = [
  {
    id: 'eq-1',
    type: 'grinder',
    brand: 'Fellow',
    model: 'Ode Gen 2',
    subType: 'flat-burr',
    settingScaleType: 'stepped-numbers',
    isFavorite: true,
    notes: '64mm Gen 2 burrs. 4.1 for standard V60.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'eq-2',
    type: 'grinder',
    brand: 'Comandante',
    model: 'C40 MK4 Nitro Blade',
    subType: 'conical-burr',
    settingScaleType: 'clicks',
    isFavorite: true,
    notes: '22-26 clicks for pour-over, 12 clicks for AeroPress.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'eq-3',
    type: 'brewer',
    brand: 'Hario',
    model: 'V60 02 (Clear Plastic)',
    subType: 'pour-over',
    isFavorite: true,
    notes: 'Plastic retains temperature best during brew.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'eq-4',
    type: 'brewer',
    brand: 'AeroPress',
    model: 'AeroPress Clear',
    subType: 'immersion',
    isFavorite: true,
    notes: 'Standard immersion with metal/paper filters.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'eq-5',
    type: 'brewer',
    brand: 'Flair',
    model: 'Flair 58+',
    subType: 'lever-espresso',
    isFavorite: true,
    notes: '58mm commercial portafilter manual lever espresso machine.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'eq-6',
    type: 'scale',
    brand: 'Timemore',
    model: 'Black Mirror Basic 2',
    subType: 'smart-scale',
    isFavorite: true,
    notes: '0.1g resolution with auto-flow rate and auto-timer.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'eq-7',
    type: 'kettle',
    brand: 'Fellow',
    model: 'Stagg EKG (0.9L)',
    subType: 'gooseneck-electric',
    isFavorite: true,
    notes: 'Precision gooseneck pour with PID temperature hold.',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_TASTING_LOGS: TastingLog[] = [
  {
    id: 'log-1',
    beanNameSnapshot: 'Worka Sakaro Anaerobic',
    roasterSnapshot: 'Sey Coffee',
    recipeNameSnapshot: 'Ultimate V60 (James Hoffmann)',
    brewMethod: 'v60',
    brewDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    coffeeDoseGrams: 30,
    waterAmountGrams: 500,
    actualTimeSeconds: 212,
    grindSetting: 'Fellow Ode 4.1',
    waterTempCelsius: 98,
    scores: {
      fragranceAroma: 9.0,
      acidity: 8.8,
      sweetness: 9.2,
      body: 7.5,
      clarity: 9.5,
      aftertaste: 8.5,
      balance: 9.0,
      overall: 9.2,
    },
    calculatedScaScore: 88.4,
    rating: 4.8,
    flavorTags: ['Jasmine', 'Peach', 'Bergamot'],
    notes: 'Vibrant acidity that cooled into intense peach nectar and jasmine tea.',
    wouldBrewAgain: true,
    createdAt: new Date().toISOString(),
  },
];
